// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqqlzbgtpcxarvmnquua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcWx6Ymd0cGN4YXJ2bW5xdXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDk0MDYsImV4cCI6MjA2MzQyNTQwNn0.VbL3sONtN4X6hkqBLVKmY0Fq1QMwWyd3JPxHreoaHCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);